version: "3.7"

volumes:
  pgdata:  
  backup:
  cache:

networks: 
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/16

services:
  db:
    image: postgres:13.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    #   - ../data:/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    tty: true
    env_file: .env
    networks:
      net:
        ipv4_address: 172.28.4.1

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    # volumes:
    # - ../data:/data
    # - cache:/cache
    expose:
      - "3000"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
    env_file: .env
    networks:
      net:
        ipv4_address: 172.28.4.2

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    # volumes: 
    #   - ../data:/data
    #   - ../app:/usr/src/app
    expose:
      - "80"
    ports:
      - "80:80"
    tty: true
    depends_on:
      - backend
    environment:
      - DEBUG=express:*
    networks:
      net:
        ipv4_address: 172.28.4.3